# Generated by Django 3.2 on 2021-05-14 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование контрагента')),
                ('date_of_contract', models.DateTimeField(verbose_name='Дата договора')),
                ('number_of_contract', models.CharField(max_length=150, verbose_name='Номер договора')),
                ('term_of_contract', models.DateTimeField(verbose_name='Срок договора')),
                ('requisites', models.CharField(max_length=500, verbose_name='Реквизиты')),
                ('intelligence', models.CharField(max_length=500, verbose_name='Сведения')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NameOfBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование Филиала')),
                ('adress', models.CharField(max_length=300, verbose_name='Адресс Филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NameOfObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование объекта')),
                ('adress', models.CharField(max_length=300, verbose_name='Адресс Филиала')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofbranch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Юзер')),
                ('report', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransferr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Передача для...')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование вида отхода')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('code_fkko', models.IntegerField(verbose_name='Код по ФККО')),
                ('danger_class', models.IntegerField(verbose_name='Класс опасности вида отхода')),
                ('origin', models.CharField(max_length=300, verbose_name='Происхождение или условия образования вида отхода')),
                ('condition', models.CharField(max_length=300, verbose_name='Агрегатное состояние и физическая форма вида отхода')),
                ('structure', models.CharField(max_length=300, verbose_name='Химический и (или) компонентный состав вида отхода, %')),
            ],
            options={
                'verbose_name': 'Отход',
                'verbose_name_plural': 'Отходы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransferredWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество, тонн')),
                ('date_of_transferred', models.DateTimeField(verbose_name='Дата образования')),
                ('user_name', models.CharField(max_length=150, verbose_name='Кто внес запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата внесения записи')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.waste', verbose_name='Наименование вида отхода')),
                ('object_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofobjects', verbose_name='Наименование объекта')),
                ('type_transferr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.typetransferr', verbose_name='Передача для...')),
            ],
            options={
                'verbose_name': 'Отход',
                'verbose_name_plural': 'Отходы',
                'ordering': ['date_of_transferred'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150, verbose_name='Подразделение')),
                ('function', models.CharField(max_length=150, verbose_name='Должность')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofbranch', verbose_name='Филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReclaimedWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество, тонн')),
                ('date_of_reclaimed', models.DateTimeField(verbose_name='Дата образования')),
                ('user_name', models.CharField(max_length=150, verbose_name='Кто внес запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата внесения записи')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.waste', verbose_name='Наименование вида отхода')),
                ('object_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofobjects', verbose_name='Наименование объекта')),
            ],
            options={
                'verbose_name': 'Отход',
                'verbose_name_plural': 'Отходы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducatedWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество, тонн')),
                ('date_of_educated', models.DateTimeField(verbose_name='Дата образования')),
                ('user_name', models.CharField(max_length=150, verbose_name='Кто внес запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата внесения записи')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.waste', verbose_name='Наименование вида отхода')),
                ('object_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofobjects', verbose_name='Наименование объекта')),
            ],
            options={
                'verbose_name': 'Отход',
                'verbose_name_plural': 'Отходы',
                'ordering': ['name'],
            },
        ),
    ]
