# Generated by Django 3.2 on 2021-05-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210517_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferredwaste',
            old_name='сounterparty',
            new_name='counterparty',
        ),
    ]
