# Generated by Django 3.2 on 2021-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20210520_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='term_of_contract',
            field=models.DateField(verbose_name='Срок договора'),
        ),
        migrations.AlterField(
            model_name='educatedwaste',
            name='date_of_educated',
            field=models.DateField(verbose_name='Дата образования'),
        ),
        migrations.AlterField(
            model_name='reclaimedwaste',
            name='date_of_reclaimed',
            field=models.DateField(verbose_name='Дата образования'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='transferredwaste',
            name='date_of_transferred',
            field=models.DateField(verbose_name='Дата образования'),
        ),
    ]
