# Generated by Django 3.2 on 2021-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20210520_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='date_of_contract',
            field=models.DateField(verbose_name='Дата договора'),
        ),
    ]
