# Generated by Django 3.2 on 2021-07-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_educatedwaste_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatedwaste',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.nameofbranch', verbose_name='Филиал'),
        ),
    ]
